- en/book.json
made navigation uniform with cocos2d-x docs
> made navigation uniform with cocos2d-x docs

- book.json
this is plugin code, please review
https://github.com/drelaptop/gitbook-plugin-github-issue-feedback/blob/master/src/plugin.js#L45
> custom feedback

- zh/book.json
Change plugins language form Traditional Chinese to Simplified Chinese
> Change plugins language

- en/_layouts/website/page.html
- zh/_layouts/website/page.html
Re: cocos-creator/creator-api-docs#24
> fixed api doc link and anchor doesn't work problem

- gulpfile.js
Re:#34
you need to update your Firedoc plugin in order to use the new command
> change the branch name Commitid

- lib/firedoc-theme/markdown/partials/field-info.mdt
#34
change the template sourceName to use another function compile the faile
> change the class link template

- book.json
#45
add the splitter plugin make sidebar could be dragged
> add the Split plugin to modfiy gitbook

- README.md
- config/cocos2d-x.org/en/styles/website.css
- config/cocos2d-x.org/zh/styles/website.css
- en/_layouts/website/header.html
- en/_layouts/website/page.html
- en/book.json
- zh/_layouts/website/header.html
- zh/_layouts/website/page.html
- zh/book.json
- zh/styles/website.css
Re:#44
add a new feature to switch API-docs version to 2.0
> add a new Nav-List to switch api version

- en/book.json
- zh/book.json
> correct the 2.0 version disappear

- lib/firedoc-theme/markdown/partials/items-index.mdt
Re:cocos-creator/creator-api-docs#43
这个和 pr /firdoc#64 是关联内容
> change the item-index. mdt

- README.md
- gulpfile.js
- package.json
> add the new festure quick preview

- en/book.json
- zh/book.json
Re:cocos-creator/creator-api-docs#44
对于路径修改
> modify the web path

- en/book.json
- zh/book.json
Re:cocos-creator/creator-api-docs#44
对于路径修改 2.0 部分
> modify the web path for 2.0

- en/_layouts/website/header.html
- en/_layouts/website/page.html
- zh/_layouts/website/header.html
- zh/_layouts/website/page.html
> correct the search feature

- en/_layouts/website/page.html
- zh/_layouts/website/page.html
> correct toggleLanguage feature

- book.json
- en/_layouts/website/header.html
- en/_layouts/website/page.html
- zh/_layouts/website/header.html
- zh/_layouts/website/page.html
1.  fix the cc.md lost enums part code problem.
2. fix the template
> Update the template

- config/cocos2d-x.org/en/book.json
- config/cocos2d-x.org/zh/book.json
- en/book.json
- en/classes/Node.md
- en/classes/Scene.md
- zh/book.json
> docs url change

- config/cocos2d-x.org/en/_layouts/website/header.html
- config/cocos2d-x.org/en/_layouts/website/page.html
- config/cocos2d-x.org/zh/_layouts/website/header.html
- config/cocos2d-x.org/zh/_layouts/website/page.html
- en/_layouts/website/header.html
- en/_layouts/website/page.html
- zh/_layouts/website/header.html
- zh/_layouts/website/page.html
> Update the url link

- gulpfile.js
- lib/tsd-generator.js
change the declare module as the declared namespace.
> change the module as the namespace

- lib/firedoc-theme/markdown/partials/class.mdt
Re: https://github.com/cocos-creator/engine/pull/4328
调整 class md 生成模板，将 example tag 标记添加。
> add example tag into class description

- gulpfile.js
> Supplementary Build finished prompt information

- book.json
https://github.com/cocos-creator/creator-docs/issues/909
> fix api url 404 error bug for cocos-creator/creator-docs/issues/909

- asset-db.md
- en/editor/asset-db.md
- zh/editor/asset-db.md
Re：https://github.com/cocos-creator/creator-api-docs/issues/158
> fix example of AssetDB.queryMetas().

- gulpfile.js
changeLog:
- 支持 jsb.d.ts 和 spine.d.ts 的构建
> support to build jsb.d.ts && spine.d.ts

- gulpfile.js
re : https://github.com/cocos-creator/engine/pull/6327
> refine tween doc

- en/book.json
- zh/book.json
1. 增加 3.0 Preview 菜单
2. 移除英文版头部 Cocos Creator 3D 的跳转链接
> 增加 3.0 Preview 菜单

- gulpfile.js
Re: https://github.com/cocos/cocos-engine/issues/11731
related pr https://github.com/cocos/cocos-engine/pull/11981
> remove TSD_FOOTER in build-tsd task
